# APPLICATION CONFIG
server:
  port: 7001
  error:
    include-message: "always"

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mugnialby/config-repository.git"
          search-paths: '{application}'